name: ShyShot
description: Photo Sharing app like Instagram made with Flutter
version: 2.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/insta_logo.png
    - assets/images/photo.jpg
  fonts:
    - family: Aveny
      fonts:
        - asset: assets/fonts/AvenyTRegular.otf
          style: normal
        - asset: assets/fonts/AvenyTMedium.otf
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf